MeuClass/Areas/Admin/Controllers/LessonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MeuClass.Areas.Admin.Controllers
{
    public class LessonController : Controller
    {
        // GET: Admin/Lesson
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AddLesson(string number)
        {
            ViewBag.Number = number;
            return View();
        }
        public ActionResult ViewLesson(string number)
        {
            ViewBag.Number = number;
            return View();
        }
    }
}

MeuClass/Controllers/UserController.cs
using MeuClass.Business.Repository;
using MeuClass.Data;
using System;
using System.Linq;
using System.Web.Mvc;

namespace MeuClass.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Profile(int number,string subview="")
        {
            var user = UserRepository.Instance.GetProfileInfo(number).Data;
            ViewBag.SubView = subview;
            return View(user);
        }

        
        public  ActionResult Edit(User user)
        {
            UserRepository.Instance._update(user);


            return Redirect(Request.UrlReferrer.ToString());
        }

        public ActionResult Search(FormCollection form)
        {

            var name = form.Get("NameSurname");
           

                return View();
           
        }
    }
}

MeuClass/Views/Shared/DoLogin.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="~/Content/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/bootstrap-theme.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/css/LoginMain.css">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <title>Giriş Sayfası</title>
</head>

<body>
    <section class="loginPage">
        @RenderBody()
    </section>
    <script src="~/Content/js/jquery-3.2.1.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
            crossorigin="anonymous"></script>
    <script src="~/Content/js/style.js"></script>
</body>

</html>

MeuClass/Views/Shared/Test.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Test</title>
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/css/LoginMain.css" rel="stylesheet" />
</head>
<body>
   @RenderBody()
</body>
</html>

MeuClass/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="~/Content/css/bootstrap.min.css">
    <link href="~/Content/css/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/css/main.css" rel="stylesheet" />
    <link rel="stylesheet" href="/Content/css/font-awesome.min.css">
    <!-- Giriş yapıldıktan sonra ki sayfalar için başka bir css dosyası kullanılacak -->
    <!--<link rel="stylesheet" type="text/css" href="~/Content/css/style.css">-->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Barlow+Semi+Condensed:400,500" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Tajawal:500" rel="stylesheet">
    <script src="~/Content/js/jquery-3.2.1.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <title>@ViewBag.Title - Sosyal Ağ</title>

    <style>
    </style>
</head>

<body style="background:#ECF0F1">
    <nav class="navbar navbar-default myNavbar">
        <div class="container-fluid padr-0 padl-0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                    aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="#menu-toggle" class="navbar-brand" id="menu-toggle">Menüyü Kapat</a>

            </div>
            <div style="background-color:#3498DB" class="collapse navbar-collapse red-text" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                </ul>
                @using (Html.BeginForm("Search", "User", FormMethod.Post, new { @class = "navbar-form navbar-left" })) {
                <div class="form-group">
                    <div id="imaginary_container">
                        <div class="input-group stylish-input-group">
                            <input type="text" class="form-control" placeholder="Ara">
                            <span class="input-group-addon">
                                <button type="submit">
                                    <span class="glyphicon glyphicon-search"></span>
                                </button>
                            </span>
                        </div>
                    </div>

                </div>
                }
                <ul class="nav navbar-nav navbar-right myNavbar-social">
                    <li role="presentation">
                        <a href="#">
                            <i class="fa fa-user" aria-hidden="true"></i>
                        </a>
                    </li>
                    <li role="presentation">
                        <a href="#">
                            <i class="fa fa-envelope-open" aria-hidden="true"></i>
                        </a>
                    </li>
                    <li role="presentation">
                        <a href="#">
                            <i class="fa fa-heart" aria-hidden="true"></i>
                            <span class="badge">3</span>
                        </a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="/img/profile.jpg" alt="" class="img-responsive img-circle profileImage">
                            <strong>@Session["name"] @Session["surname"]</strong>
                            <span class="glyphicon glyphicon-chevron-down"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <div class="myNavbar-login">
                                    <div class="row">
                                        <div class="col-lg-4">
                                            <p class="text-center">
                                                <span class="glyphicon glyphicon-user icon-size"></span>
                                            </p>
                                        </div>
                                        <div class="col-lg-8">
                                            <p class="text-left">
                                                <strong>@Session["name"] @Session["surname"]</strong>
                                            </p>
                                            <p class="text-left">
                                                <a href="#" class="btn btn-primary btn-block btn-sm">Ayarlar</a>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <div class="myNavbar-login navbar-login-session">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <p>

                                                @Html.ActionLink("Çıkış Yap","Logout","Home",new { area =""},new {@class="btn btn-danger btn-block"})
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
     <div class="container-fluid">
    <div id="wrapper" class="toggled">
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="http://localhost:55007/">
                        Mersin Üniversitesi
                    </a>
                </li>
                <li>
                    <a href="http://localhost:55007/">Anasayfa</a>
                </li>
                <li>
                    <a href="/Profile/@Session["user_id"]">Profil</a>
                </li>
                <li>
                    <a href="#">Sınıflar</a>
                </li>
                <li>
                    <a href="#">Ders Programı</a>
                </li>
                <li>
                    <a href="#">Teslim Tarihleri</a>
                </li>
                <li>
                    <a href="#">Ayarlar</a>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
       
            <div id="page-content-wrapper">
                <div class="col-xs-7 ">
                    @RenderBody()
                </div>
                <div class="col-xs-3">
                    <div class="panel indexProfileBox">
                        <div class="panel-body">
                            <div class="col-xs-3">
                                <img src="/Content/img/users/noImage.png" alt="" class="img-responsive">
                            </div>
                            <div class="col-sm-9 indexProfileBox-Text">
                                <h4>@Session["name"] @Session["surname"]</h4>
                                <h5>Öğrenci - Mersin Üniversitesi</h5>
                            </div>
                        </div>
                    </div>
                    @{ Html.RenderAction("MainPageSide", "Lesson", new { area = "Partial" }); }
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->
    </div>


    <script src="~/Content/js/bootstrap.min.js"></script>
    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
    </script>


</body>

</html>